#!/bin/bash

# Executes a command repeatedly and sometimes prints a random cheat code until
# the command returns 0, in which case it prints the konami code followed by the
# result of the command.

step=5  # Number of command executions before printing a cheat code

btns='↑↓←→AB'
konami='↑ ↑ ↓ ↓ ← → ← → B A'

# Output a single random button
rb() {
  rnd=$((RANDOM % ${#btns} + 1))
  u32c=4  # number of bytes in a UTF-32 char
  echo $btns | iconv -t UTF-32 | \
    head -c $((rnd * u32c + u32c)) | tail -c $u32c | \
    iconv -f UTF-32
}

# Try to output the konami code, but never succeed
konami_try() {
  try="$konami"
  until [ "$try" != "$konami" ]; do
    try="$(rb) $(rb) $(rb) $(rb) $(rb) $(rb) $(rb) $(rb) $(rb) $(rb)"
  done

  echo "$try"
}


while ! ((stop)); do
  if out="$("$@")"; then
    echo "$konami"
    echo "$out"
    stop=1
  else
    sleep 1s
    if ! (( (iter + 1) % step )); then
      konami_try
    fi
    ((iter++))
  fi
done
